version: "3.8"

services:
  master:
    image: postgres:latest
    container_name: pg_master
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./config/master/init:/docker-entrypoint-initdb.d
      - ./config/master/data:/var/lib/postgresql/data

  postgres-exporter:
    image: bitnami/postgres-exporter:0.15.0
    links:
        - master
    environment:
      DATA_SOURCE_NAME: postgresql://grafana:postgres@master:5432/grafana?sslmode=disable

  app:
    build: .
    container_name: app
    ports:
      - "8081:8081"
      - "5001:5001"
    depends_on:
      - master
    environment:
      DB_URL: postgresql://postgres:postgres@localhost:5432/app?sslmode=disable
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 8879:9090
    volumes:
      - ./config/prometheus/data:/mnt/user/appdata/prometheus/data
      - ./config/prometheus/prometheus.yml:/mnt/user/appdata/prometheus/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: master:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
